[book]
title = "Duende: Cross-Platform Daemon Framework"
authors = ["PAIML"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "../target/book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/paiml/duende"
edit-url-template = "https://github.com/paiml/duende/edit/main/book/{path}"
site-url = "/duende/"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
